
import java.io.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */

public class Destego_second extends javax.swing.JFrame {
String ofile;
byte[] buff;
String emess;
String mess;
String key;
byte []keyArr;
byte []messArr;
int a,i,j;
    /**
     * Creates new form Destego_second
     */
    public Destego_second(String of,String k) {
        initComponents();
       ofile=of;
       key=k;
    }

    private Destego_second() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Processing...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
Destego_message a=new Destego_message(mess);
a.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        {InputStream fis = null;
        try {
            jTextArea1.append("\nconverting wave file to byte array");
            File file = new File(ofile);
            fis = new FileInputStream(file);
            buff = new byte[(int)file.length()];
            fis.read(buff, 0, buff.length);
            fis.close();
        }
       
        catch (FileNotFoundException ex) {
           jTextArea1.append("\ncannot convert wave file to byte array FNFE");
        }   catch (IOException ex) {
               jTextArea1.append("\ncannot convert wave file to byte array IOE");
            } finally {
            try {
                fis.close();
            } catch (IOException ex) {
                jTextArea1.append("\ncannot convert wave file to byte array IOE");
            }
        } 
        }
        {jTextArea1.append("\nconvert key to byte array");
try
		{
			ByteArrayOutputStream byteOut= new ByteArrayOutputStream();
			keyArr= key.getBytes();
			
}
catch(Exception e)
{jTextArea1.append("\n"+e);
}
}
        { jTextArea1.append("\nobtaining decrypted message from wave file");
       for (i = 0,j = 0;i < buff.length;)
       {if (buff[i++] != keyArr[j++])
       {
           j = 0;
           continue;
       }
       if (j == keyArr.length)
       {
           jTextArea1.append("\nmessage found"); 
           break;
       }
       if(i==buff.length)
          jTextArea1.append("\nno message found"); 


       }
       messArr=new byte[buff.length-i];
       for(int k=i;k<buff.length;k++){
       messArr[k-i]=buff[k];    
       }
       }
        {  jTextArea1.append("\nconverting message to string");    
            emess = new String(messArr);
        
        }
       { jTextArea1.append("\ndecrypting secret message");
        if(emess == null)
         jTextArea1.append("\nNo Message Found");
     char[] digit = emess.toUpperCase().toCharArray();
       for(int i = 0; i < digit.length; i++) {
          if(digit[i] < 'A' || digit[i] > 'Z') {
               continue;
           }
          digit[i] = Character.toLowerCase(digit[i]);
          digit[i] -= 6;
           if(digit[i] < 'a') {
                digit[i] += 'z';
                digit[i] -= ('a' - 1);         
            }
        }
        mess=new String(digit);
        jTextArea1.append("\nMESSAGE DECRYPTED");
       }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Destego_second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Destego_second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Destego_second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Destego_second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Destego_second().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
